import os
import re
import asyncio
from typing import Literal, List
from concurrent.futures import ThreadPoolExecutor

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from huggingface_hub import InferenceClient
from pydantic import BaseModel, Field

from spell_cleaner import (
    robust_sentence_split,
    local_textrank_summarize
)

load_dotenv()

app = FastAPI(
    title="Document Summary Assistant API",
    version="4.0.0",
    description="Production API with strict BPE artifact removal and case normalization."
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"]
)

hf_token = os.getenv("HF_TOKEN")
client = InferenceClient(api_key=hf_token) if hf_token else None

SUMMARIZER_MODEL = "facebook/bart-large-cnn"
GRAMMAR_MODEL = "vennify/t5-base-grammar-correction"

executor = ThreadPoolExecutor(max_workers=4)

LENGTH_PRESETS = {
    "short": {"max_length": 80, "min_length": 30, "key_points_count": 2},
    "medium": {"max_length": 150, "min_length": 60, "key_points_count": 3},
    "long": {"max_length": 300, "min_length": 120, "key_points_count": 5},
}


class SummaryRequest(BaseModel):
    text: str = Field(..., min_length=15, description="Document text to summarize.")
    length: Literal["short", "medium", "long"] = "medium"


class SummaryResponse(BaseModel):
    summary: str
    key_points: List[str]


def clean_bpe_and_utf8_artifacts(text: str) -> str:
    """
    Strips tokenizer/BPE artifacts, broken UTF-8 byte symbols, 
    and gibberish non-ASCII characters generated by BART/T5 models.
    """
    if not text:
        return ""

    # 1. Remove BPE token artifacts (e.g. Ġ, Â, Ã, , ##)
    text = re.sub(r'[ĠÂÃâ€™â€œâ€\x80-\xff]', '', text)
    text = re.sub(r'', '', text)
    text = re.sub(r'##\w+', '', text)  # WordPiece leftover fragments

    # 2. Fix broken quotes and symbols
    text = text.replace('&amp;', '&').replace('&lt;', '<').replace('&gt;', '>')
    
    # 3. Join separated contractions (e.g. "don ' t" -> "don't")
    text = re.sub(r"(\w+)\s+'\s+(s|t|re|ve|m|ll|d)\b", r"\1'\2", text, flags=re.IGNORECASE)

    # 4. Filter out meaningless single-character non-English noise tokens
    words = text.split()
    filtered_words = []
    for w in words:
        # Keep word if it's alphanumeric/punctuation or standard English 'a'/'I'
        if len(w) == 1 and w not in ["a", "A", "I", "i", ".", ",", "-", ":", ";"]:
            continue
        filtered_words.append(w)
    
    text = " ".join(filtered_words)
    return text.strip()


def normalize_capitalization_and_spacing(text: str) -> str:
    """
    Fixes random uppercase words (e.g. "The DOCTOR Went TO the Hospital")
    and enforces proper sentence-case formatting.
    """
    if not text:
        return ""

    # 1. Fix spacing around punctuation (e.g., "hello . World" -> "hello. World")
    text = re.sub(r'\s+([.,!?;:])', r'\1', text)
    text = re.sub(r'([.,!?;:])(?=[A-Za-z])', r'\1 ', text)
    
    # 2. Convert random fully UPPERCASE non-acronym words back to lowercase.
    # Words with 2-4 uppercase characters like "NASA", "AI", "PDF" are kept as acronyms.
    def replace_random_caps(match):
        word = match.group(0)
        # Keep known acronyms (2-4 chars) untouched
        if len(word) <= 4 and word.isupper():
            return word
        # Otherwise lowercase it
        return word.lower()

    # Find words where all letters are uppercase
    text = re.sub(r'\b[A-Z]{2,}\b', replace_random_caps, text)

    # 3. Enforce Sentence Case after punctuation
    sentences = robust_sentence_split(text)
    fixed_sentences = []
    
    for s in sentences:
        s = s.strip()
        if not s:
            continue
        # Lowercase everything except first character and preserved acronyms
        # Keep capitalization intact only for the first word
        first_char = s[0].upper()
        rest = s[1:]
        
        # Combine and ensure terminal punctuation
        s_clean = first_char + rest
        if not s_clean.endswith(('.', '!', '?')):
            s_clean += '.'
        fixed_sentences.append(s_clean)

    return " ".join(fixed_sentences)


def deep_text_repair(text: str) -> str:
    """Pre-cleans raw document text before feeding it to models."""
    if not text:
        return ""

    # Fix broken lines & hyphens
    text = re.sub(r'(\w+)-\s*\n\s*(\w+)', r'\1\2', text)
    text = re.sub(r'(?<!\n)\n(?!\n)', ' ', text)
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()


@app.get("/health", tags=["Health"])
async def health():
    return {"status": "ok", "hf_client_active": client is not None}


@app.post("/api/summarize", response_model=SummaryResponse, tags=["Summarization"])
async def summarize(request: SummaryRequest):
    raw_text = request.text.strip()
    if not raw_text:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No document text provided."
        )

    loop = asyncio.get_running_loop()

    # Step 1: Deep text repair on input
    cleaned_input = await loop.run_in_executor(executor, deep_text_repair, raw_text[:12000])
    length_cfg = LENGTH_PRESETS[request.length]

    # Step 2: Extractive filtering for large texts
    if len(cleaned_input.split()) > 350:
        filtered_input, _ = await loop.run_in_executor(
            executor, local_textrank_summarize, cleaned_input, request.length
        )
    else:
        filtered_input = cleaned_input

    raw_summary = ""

    # Step 3: BART Abstractive Summarization
    if client:
        try:
            res = await loop.run_in_executor(
                executor,
                lambda: client.summarization(
                    text=filtered_input,
                    model=SUMMARIZER_MODEL,
                    parameters={
                        "max_length": length_cfg["max_length"],
                        "min_length": length_cfg["min_length"],
                        "do_sample": False
                    }
                )
            )
            extracted = res.summary_text.strip() if hasattr(res, "summary_text") else str(res).strip()
            if len(extracted) > 20:
                raw_summary = extracted
        except Exception as err:
            print(f"[Warning] Summarizer fallback triggered: {err}")

    # Fallback to TextRank if BART fails
    if not raw_summary:
        raw_summary, _ = await loop.run_in_executor(
            executor, local_textrank_summarize, cleaned_input, request.length
        )

    # Step 4: Multi-pass Artifact Cleaning & Capitalization Normalization
    # 4a. Strip Byte-Pair artifacts and garbage tokens
    clean_text = await loop.run_in_executor(executor, clean_bpe_and_utf8_artifacts, raw_summary)
    
    # 4b. Enforce clean sentence casing and fix random capitalized words
    polished_summary = await loop.run_in_executor(executor, normalize_capitalization_and_spacing, clean_text)

    # Step 5: Clean Key Points extraction
    raw_sentences = robust_sentence_split(polished_summary)
    
    # Filter out empty or broken sentence fragments
    valid_sentences = [
        s for s in raw_sentences 
        if len(s.split()) >= 4 and not re.search(r'[^\w\s.,!\?\'\-]', s)
    ]

    target_count = length_cfg["key_points_count"]
    key_points = valid_sentences[:target_count] if valid_sentences else [polished_summary]

    return SummaryResponse(
        summary=polished_summary,
        key_points=key_points
    )
